defaults:
  - _self_
  - checkpoint: last_k
  - data: default
  - logger: jh
  - model: default
  - optimizer: adamw
  - trainer: train
  - decode: default
exp_name: 
exp_dir: 
num_workers: 12
gpus: 
slurm_job_id:
train: True
log_wandb: True
infer_path:
ckpt_path:
transfer_frontend:
sp_model_path:
dict_path:
intialize_dict: True